config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
	resources :users, except: :show do
		collection do
	    	get :newuser
	 	 end
	end
 	devise_for :users , :skip => [:registrations]
 	resources :student_profiles
 	resources :teacher_profile
 	resources :s_class
 	resources :subject
 	resources :course
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :all                 # allow everyone to read everything
    return unless user && user.admin?
    can :access, :rails_admin       # only allow admin users to access Rails Admin
    can :dashboard, :all            # allow access to dashboard
    if user.role? :Superadmin
      can :manage, :all   
    if user.role? :CoAdmin
      can :manage, :all             # allow superadmins to do anything
    elsif user.role? :Employee
      can :manage, [User, Product]  # allow managers to do anything to products and users
    elsif user.role? :Student
      can :update, Product, hidden: false  # allow sales to only update visible products
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/s_class.rb
class SClass < ApplicationRecord
	has_many :subjectclass
	has_many :subject, :through => :subjectclass
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
	belongs_to :user 
	accepts_nested_attributes_for :user, :allow_destroy => true
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :subjectclass
	has_many :s_class, :through => :subjectclass
end

app/models/subjectclass.rb
class Subjectclass < ApplicationRecord
	belongs_to :s_class
	belongs to :sublect
end

app/models/teacher_profile.rb
class TeacherProfile < ApplicationRecord
	belongs_to :user 
	accepts_nested_attributes_for :user, :allow_destroy => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
   belongs_to :role 
   has_one :student_profile
   has_one :teacher_profile
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
	before_action :authenticate_user!
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in? 
  		redirect_to users_path
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/controllers/s_class_controller.rb
class SClassController < ApplicationController
	
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
	before_action :authenticate_user!
	def index
		@sclass = SClass.all
	  @subject = Subject.all
	end

	def new
	 @sclass = SClass.new
	 @subject = Subject.new
	 
	end

	def create 
		binding.pry
	  @sclass=SClass.new(sclass_params)
	  if @sclass.save
	  @subject = Subject.new(subject_params)
	     if@subject.save 
	      respond_to do |format|
	       format.html { redirect_to course_index_url, notice: 'User was successfully created.' }
	       format.json { render :show, status: :created, location:@subject}
	     else
	       format.html { render :new }
	       format.json { render json:@subject.errors, status: :unprocessable_entity }
	     end
	  end
	end
	end

	def show
	end

	def subject_params
	 params.require(:subject).permit(:name, id:[])
	end

	def sclass_params
	 params.require(:sclass).permit(:name, :section, id:[])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
	end

	def new
    @user=User.all
	end

	def newuser
		@user=User.new
	end

	def show
	end
	
	def create
    #binding.pry
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
     end
    end
    
    def destroy
 		 signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
  	 # set_flash_message! :notice, :signed_out if signed_out
  		 yield if block_given?
  		 #respond_to_on_destroy
        if signed_out
         redirect_to new_user_session_path
       end
	  end

	def user_params
       params.require(:user).permit(:name, :email,:f_name,:l_name,:fathername,:gender,:dob,:phonenumber,:city, :address, :password,:zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/s_class_helper.rb
module SClassHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/teacher_profile_helper.rb
module TeacherProfileHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/userlists_helper.rb
module UserlistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div id="page-wrapper">
      <div class="main-page">
       <%= link_to "New User" , newuser_users_path ,:class => "button3"%><br><br>
       		<input size="40" type="text" placeholder="Search"/><br><input type="submit" class="button3" name="submit">
      				<br>
       				<br>
       		<div class="tables">
					<h3 class="title1">User List</h3>
					<div class="panel-body widget-shadow">
						<table class="table">
							<thead>
								<tr>
								  <th>User Id</th>
								  <th>Name</th>
								  <th>Email</th>
								</tr>
							</thead>
							
							<tbody>
							<% @user.each do |u| %>
							<%= simple_form_for User.new do |f| %>
								<tr>
								  <td><%= u.id %></td>
								  <td><%= u.f_name %></td>
								  <td><%= u.email %></td>
								  <td><%= f.collection_select :role_id, Role.order(:name),:id,:name, include_blank: false %><button class="button3">Update</button>
								</td>
								</tr>
							</tbody>
							<% end %>
							<% end %>
						</table>
					</div>
					</div>
					</div>
      <div class="clearfix"> </div> 
</div>

app/views/users/newuser.html.erb
<div id="page-wrapper">
	<div class="main-page">
        <h3 class="title1" align="center">Add New User</h3>
		<%= simple_form_for @user do |f| %>
        <div class="login-page">
         <%= f.input :f_name, required: false,label: 'First Name'%>
 		 <%= f.input :l_name,label: 'Last Name' %>
         <%= f.input :gender, as: :radio_buttons, :collection => [ ['Male', "Male"], ['Female', "Female"] ], :checked => ['Yes', true] %> 
  		 <%= f.input :fathername %>
         <%= f.input :dob, as: :date, html5: true,label: 'Date of Birth'%>
         <%= f.input :email %>
         <%= f.input :password %>
         <%= f.input :phonenumber %>
         <%= f.input :address %>
         <%= f.input :zipcode %>
         <%= f.input :city %>
  		 <%= f.button :submit %>
		<% end %>
        </div>
		<div class="clearfix"> </div>
	</div>
</div>